
	<link rel="home" href="http://craft.laundryrepublic.dev/" />

	<meta charset="utf-8">
	<title>Laundryrepublic</title>
	
	<!-- <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed" rel="stylesheet" /> -->

	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:600,600i|Montserrat:700|Roboto:400,400i,700,700i" rel="stylesheet">
	
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- <link rel="stylesheet" type="text/css" href="/css/normalize.css" /> -->
	<!-- <link rel="stylesheet" type="text/css" href="/css/webflow.css" /> -->
	<!-- <link rel="stylesheet" type="text/css" href="/resources/plugins/toastr/toastr.min.css" /> -->
	
	<link rel="stylesheet" type="text/css" href="/dist/main.css" />
	<!-- <link rel="stylesheet" type="text/css" href="/css/laundryrepublic.css" /> -->
	<link rel="stylesheet" href="http://basehold.it/24">

	<!-- <link rel="stylesheet" type="text/css" href="/resources/css/switches.css" /> -->
  <!--
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script>
    WebFont.load({
      google: {
        families: ["Nunito:regular,700"]
      }
    });
  </script>
  -->
  <!-- <script type="text/javascript" src="/js/modernizr.js"></script> -->
  	<link rel="shortcut icon" type="image/x-icon" href="https://daks2k3a4ib2z.cloudfront.net/img/favicon.ico">
  	<link rel="apple-touch-icon" href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png">
  
 
	<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> -->
	<!-- <script type="text/javascript" src="/resources/plugins/toastr/toastr.min.js"></script> -->
	
	<!-- <script type="text/javascript" src="/js/webflow.js"></script> -->
	
	<script type="text/javascript" src="/js/global.js"></script>
	
	<!--[if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->	
		
	