<div class="w-section section header-section">

    <div class="w-clearfix wide-container">
      <a class="w-nav-brand main-logo" href="index"><img class="logo-image" src="/images/LR-logo-horiz.png">
      </a>
      <div class="w-hidden-small w-hidden-tiny desktop-phone-no">020 7193 3130</div>
      <div class="w-nav main-mavbar" data-animation="default" data-collapse="medium" data-contain="1" data-duration="400">
        <div class="w-container main-nav-container">
          <nav class="w-nav-menu main-nav-menu" role="navigation">
						  <a class="w-nav-link main-menu-item"  href="http://craft.laundryrepublic.dev/" title="Home">Home</a>
						  <a class="w-nav-link main-menu-item"  href="http://craft.laundryrepublic.dev/order.php" title="Order now">Order now</a>
						  <a class="w-nav-link main-menu-item"  href="http://craft.laundryrepublic.dev/how-it-works.php" title="How it works">How it works</a>
						  <a class="w-nav-link main-menu-item"  href="http://craft.laundryrepublic.dev/prices.php" title="Prices">Prices</a>
						  <a class="w-nav-link main-menu-item"  href="http://craft.laundryrepublic.dev/faqs/how-do-i-pay-for-my-order.php" title="FAQ">FAQ</a>
		  		    <a class="w-nav-link main-menu-item" href="/?login">Login</a>
          </nav>
          <div class="w-nav-button menu-button" data-ix="navbar-closed">
            <div class="menu-icon"></div>
            <div class="open-menu-icon"></div>
          </div>
          <!-- /.menu-button -->
        </div>
        <!-- /.main-nav-container -->
      </div>
      <!-- /.main-mavbar -->
    </div>
    <!-- /.wide-container -->

</div>
<!-- /.header-section -->

<div class="header-phone"><a class="my-account-mobile" href="#">My account</a>
  <div class="mobile-phone-number">020 7193 3130</div>
</div>